### PR TITLE
added the input style

### PR DESCRIPTION
**Pull request by Evangel2020**

### CODE REVIEW

**Review by Codeindeed — APPROVED** [review]
I'll merge this request but i'm not closing the issue due to it's you are not done with the responsiveness

**Comment by Codeindeed** [comment]
tried running your code on my system and ran into issues merge new commits and open pull requests again please

**Comment by Evangel2020** [comment]
> I'll merge this request but i'm not closing the issue due to it's you are not done with the responsiveness

Ok

**Comment by Evangel2020** [comment]
> tried running your code on my system and ran into issues merge new commits and open pull requests again please

Do you mean it couldn't  merge or what??

**Pull request closed without merging**
