### PR TITLE
fix:forget password functionality added

### PR DESCRIPTION
**Pull request by ankitraj10**
-Added a new file **userAccount.js** in util folder ,It serves api request for reset password
-Created function name  **handleForgetPass**  in login.js file , It will get called on click of forget password text.

  Note -: Added dummy alert on forget password api call as API  fetch getting failed due to dummy id parameters.
  #19

### CODE REVIEW

**Review by Codeindeed — COMMENTED** [review]
On review will merge once it's done

**Review by Codeindeed — CHANGES_REQUESTED** [review]
write a conditional if there is no email used and there is no id used for the API do the minor changes and create a pull request

**Comment by ankitraj10** [comment]
Hi @Codeindeed  ,I have added validation for email and user ID for reset password api call ,Please validate and let me know if you require any other changes in my code.Thanks !!

**Review by Codeindeed — CHANGES_REQUESTED** [review]
https://fastrash-1337.ew.r.appspot.com/api-docs/#/Authentication/post_api_auth_org_resetpassword_

In this documentation, user Id is not required so you have to remove the area of the user Id to be able to make a good API call

**Comment by ankitraj10** [comment]
Yes ,Rightly mentioned .I have removed id form API call and updated PR ,Please take a review .Thanks !!

**Review by Codeindeed — CHANGES_REQUESTED** [review]
Thank you for the necessary changes but there are still errors to fix such as you are not using the proper API which is this ("https://fastrash-1337.ew.r.appspot.com/api/auth/org/resetpassword") also your responses should return an alert for now instead of an object because it's not a loader I've done the changes but would be nice you do it from your end so that I can audit and merge.

**Comment by ankitraj10** [comment]
Hi @Codeindeed  , I have done few changes in code - :
- Now resetPassword function return alert instead of object 
- Alert is still a dummy alert as i do not have testing mail id for reset password , so validation not added for alert.
- API string i have matched , it seems fine but you can have a look again n let me know if it require some more changes.

**Review by Codeindeed — APPROVED** [review]
Thanks for the changes

**Pull request merged**
